# Production configuration for the Distributed Caching System

cache:
  type: in-memory
  max_size: 10GB        
  eviction_policy: LRU   
  persistent_store: SSD  
  serialization: protobuf 

distributed:
  replication:
    strategy: multi-master     
    conflict_resolution: vector-clocks  
  partitioning:
    strategy: consistent-hashing  
  nodes:
    - host: cache-node-01
      port: 6379
      weight: 1
    - host: cache-node-02
      port: 6379
      weight: 1
    - host: cache-node-03
      port: 6379
      weight: 1

consistency:
  model: quorum  
  read_quorum: 2    
  write_quorum: 3   

security:
  authentication:
    type: jwt
    token_expiry: 3600  
  authorization:
    roles:
      - name: admin
        permissions: all
      - name: user
        permissions: read, write
  encryption:
    data_encryption: true 
    tls_enabled: true      

monitoring:
  enabled: true
  metrics_exporter: prometheus  
  alerting_rules_file: /monitoring/alerting/AlertRules.yaml 
  logging:
    level: info    
    output: /var/log/cache_system.log  

failover:
  enabled: true
  detection_timeout: 5s    
  failover_strategy: auto  

networking:
  rpc_protocol: grpc    
  rpc_port: 8080
  max_request_timeout: 30s  

deployment:
  orchestration: kubernetes  
  replicas: 3              

backup:
  schedule: daily   
  backup_store: /data/backups  

environment:
  name: production
  region: us-east-1
  availability_zone: us-east-1a